/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangelogregoriogarathread;

import javax.swing.JOptionPane;

/**
 *
 * @author dange
 */
public class FrameInizio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameInizio.class.getName());

    private String calciatoreScelto = "";
    /**
     * Creates new form FrameInizio
     */
    public FrameInizio() {
        initComponents();
    }

    private void resettaColori() {
    panelMessi.setBackground(new java.awt.Color(20,60,20));
    panelRonaldo.setBackground(new java.awt.Color(20,60,20));
    panelHaaland.setBackground(new java.awt.Color(20,60,20));
    panelNeymar.setBackground(new java.awt.Color(20,60,20));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAvvia = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelMessi = new javax.swing.JPanel();
        lblMessiImg = new javax.swing.JLabel();
        lblMessiTesto = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelRonaldo = new javax.swing.JPanel();
        lblRonaldoImg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        panelHaaland = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        panelNeymar = new javax.swing.JPanel();
        lblNeymarImg = new javax.swing.JLabel();
        lblNeymarTesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        lblTitolo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(20, 60, 20));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Scegli il tuo calciatore!");
        lblTitolo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAvvia.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        btnAvvia.setForeground(new java.awt.Color(20, 60, 20));
        btnAvvia.setText("Avvia Gara");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAvvia, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(20, 60, 20));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        panelMessi.setBackground(new java.awt.Color(20, 60, 20));
        panelMessi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMessiMouseClicked(evt);
            }
        });

        lblMessiImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/messiInizio.png"))); // NOI18N

        lblMessiTesto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMessiTesto.setForeground(new java.awt.Color(255, 255, 255));
        lblMessiTesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessiTesto.setText("MESSI");
        lblMessiTesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelMessiLayout = new javax.swing.GroupLayout(panelMessi);
        panelMessi.setLayout(panelMessiLayout);
        panelMessiLayout.setHorizontalGroup(
            panelMessiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMessiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMessiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessiTesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMessiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblMessiImg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelMessiLayout.setVerticalGroup(
            panelMessiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMessiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessiImg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessiTesto, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(panelMessi, new java.awt.GridBagConstraints());

        jPanel5.setBackground(new java.awt.Color(20, 60, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new java.awt.GridBagConstraints());

        panelRonaldo.setBackground(new java.awt.Color(20, 60, 20));
        panelRonaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRonaldoMouseClicked(evt);
            }
        });

        lblRonaldoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/ronaldoInizio.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RONALDO");

        javax.swing.GroupLayout panelRonaldoLayout = new javax.swing.GroupLayout(panelRonaldo);
        panelRonaldo.setLayout(panelRonaldoLayout);
        panelRonaldoLayout.setHorizontalGroup(
            panelRonaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRonaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRonaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRonaldoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblRonaldoImg))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRonaldoLayout.setVerticalGroup(
            panelRonaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRonaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRonaldoImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(panelRonaldo, new java.awt.GridBagConstraints());

        jPanel7.setBackground(new java.awt.Color(20, 60, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new java.awt.GridBagConstraints());

        panelHaaland.setBackground(new java.awt.Color(20, 60, 20));
        panelHaaland.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHaalandMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/haalandInizio.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HAALAND");

        javax.swing.GroupLayout panelHaalandLayout = new javax.swing.GroupLayout(panelHaaland);
        panelHaaland.setLayout(panelHaalandLayout);
        panelHaalandLayout.setHorizontalGroup(
            panelHaalandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHaalandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHaalandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHaalandLayout.setVerticalGroup(
            panelHaalandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHaalandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(panelHaaland, new java.awt.GridBagConstraints());

        jPanel9.setBackground(new java.awt.Color(20, 60, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, new java.awt.GridBagConstraints());

        panelNeymar.setBackground(new java.awt.Color(20, 60, 20));
        panelNeymar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNeymarMouseClicked(evt);
            }
        });

        lblNeymarImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/neymarInizio.png"))); // NOI18N

        lblNeymarTesto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNeymarTesto.setForeground(new java.awt.Color(255, 255, 255));
        lblNeymarTesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNeymarTesto.setText("NEYMAR JR");

        javax.swing.GroupLayout panelNeymarLayout = new javax.swing.GroupLayout(panelNeymar);
        panelNeymar.setLayout(panelNeymarLayout);
        panelNeymarLayout.setHorizontalGroup(
            panelNeymarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNeymarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNeymarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNeymarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNeymarImg))
                    .addComponent(lblNeymarTesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelNeymarLayout.setVerticalGroup(
            panelNeymarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNeymarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNeymarImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNeymarTesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(panelNeymar, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMessiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMessiMouseClicked
    resettaColori();
    panelMessi.setBackground(new java.awt.Color(153,204,255));
    calciatoreScelto = "Messi";
    }//GEN-LAST:event_panelMessiMouseClicked

    private void panelRonaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRonaldoMouseClicked
    resettaColori();
    panelRonaldo.setBackground(new java.awt.Color(153,204,255));
    calciatoreScelto = "Ronaldo";
    }//GEN-LAST:event_panelRonaldoMouseClicked

    private void panelHaalandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHaalandMouseClicked
    resettaColori();
    panelHaaland.setBackground(new java.awt.Color(153,204,255));
    calciatoreScelto = "Haaland";
    }//GEN-LAST:event_panelHaalandMouseClicked

    private void panelNeymarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNeymarMouseClicked
    resettaColori();
    panelNeymar.setBackground(new java.awt.Color(153,204,255));
    calciatoreScelto = "Neymar";
    }//GEN-LAST:event_panelNeymarMouseClicked

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed

    if (calciatoreScelto.equals("")) {
        JOptionPane.showMessageDialog(this, "Seleziona un calciatore prima di iniziare!");
        return;
    }
    FrameGara gara = new FrameGara(calciatoreScelto);
    gara.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAvviaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblMessiImg;
    private javax.swing.JLabel lblMessiTesto;
    private javax.swing.JLabel lblNeymarImg;
    private javax.swing.JLabel lblNeymarTesto;
    private javax.swing.JLabel lblRonaldoImg;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel panelHaaland;
    private javax.swing.JPanel panelMessi;
    private javax.swing.JPanel panelNeymar;
    private javax.swing.JPanel panelRonaldo;
    // End of variables declaration//GEN-END:variables
}
