/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangelogregoriogarathread;

import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
/**
 *
 * @author dange
 */
public class FrameGara extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameGara.class.getName());

    private static final int PASSI_ARRIVO = 70;
    private String calciatoreSelezionato;

    private final Map<String, JLabel>       immaginiCalciatori = new LinkedHashMap<>();
    private final Map<String, JProgressBar> barreAvanzamento   = new LinkedHashMap<>();

    private final List<String>  classificaFinale = new ArrayList<>();
    private final StringBuilder testoAvvenimenti = new StringBuilder();
    private int postoCorrente = 1;

    
    /**
     * Creates new form FrameGara
     */
    public FrameGara(String nomeCalciatore) {
    this.calciatoreSelezionato = nomeCalciatore;
    initComponents();
    collegaComponenti();
    avviaGara();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTu = new javax.swing.JLabel();
        labelTuImg = new javax.swing.JLabel();
        panelDestra = new javax.swing.JPanel();
        panelClassifica = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelImprevisti = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panelGara = new javax.swing.JPanel();
        ProgressBarMessi = new javax.swing.JProgressBar();
        ProgressBarNeymar = new javax.swing.JProgressBar();
        ProgressBarRonaldo = new javax.swing.JProgressBar();
        ProgressBarHaaland = new javax.swing.JProgressBar();
        lblMessiGara = new javax.swing.JLabel();
        lblRonaldoGara = new javax.swing.JLabel();
        lblHaalandGara = new javax.swing.JLabel();
        lblNeymarGara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 40, 10));

        lblTu.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTu.setForeground(new java.awt.Color(255, 255, 255));
        lblTu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTu.setText("TU: ");
        lblTu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTu, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(labelTuImg, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1086, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTu, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTuImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelDestra.setBackground(new java.awt.Color(10, 40, 10));
        panelDestra.setPreferredSize(new java.awt.Dimension(350, 0));

        panelClassifica.setBackground(new java.awt.Color(10, 40, 10));
        panelClassifica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLASSIFICA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelClassificaLayout = new javax.swing.GroupLayout(panelClassifica);
        panelClassifica.setLayout(panelClassificaLayout);
        panelClassificaLayout.setHorizontalGroup(
            panelClassificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClassificaLayout.setVerticalGroup(
            panelClassificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClassificaLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelImprevisti.setBackground(new java.awt.Color(10, 40, 10));
        panelImprevisti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AVVENIMENTI");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout panelImprevistiLayout = new javax.swing.GroupLayout(panelImprevisti);
        panelImprevisti.setLayout(panelImprevistiLayout);
        panelImprevistiLayout.setHorizontalGroup(
            panelImprevistiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImprevistiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelImprevistiLayout.setVerticalGroup(
            panelImprevistiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprevistiLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDestraLayout = new javax.swing.GroupLayout(panelDestra);
        panelDestra.setLayout(panelDestraLayout);
        panelDestraLayout.setHorizontalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelClassifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelImprevisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDestraLayout.setVerticalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestraLayout.createSequentialGroup()
                .addComponent(panelClassifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImprevisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelDestra, java.awt.BorderLayout.LINE_END);

        panelGara.setBackground(new java.awt.Color(20, 60, 20));

        lblMessiGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/messiCorre.png"))); // NOI18N

        lblRonaldoGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/ronaldoCorre.png"))); // NOI18N

        lblHaalandGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/haalandCorre.png"))); // NOI18N

        lblNeymarGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/neymarCorre.png"))); // NOI18N

        javax.swing.GroupLayout panelGaraLayout = new javax.swing.GroupLayout(panelGara);
        panelGara.setLayout(panelGaraLayout);
        panelGaraLayout.setHorizontalGroup(
            panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGaraLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addComponent(lblMessiGara)
                        .addGap(70, 70, 70)
                        .addComponent(lblRonaldoGara)
                        .addGroup(panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGaraLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblHaalandGara))
                            .addGroup(panelGaraLayout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(lblNeymarGara)))
                        .addContainerGap(448, Short.MAX_VALUE))
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addGroup(panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProgressBarNeymar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProgressBarHaaland, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProgressBarRonaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProgressBarMessi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        panelGaraLayout.setVerticalGroup(
            panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGaraLayout.createSequentialGroup()
                .addGroup(panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessiGara)
                            .addComponent(lblNeymarGara)))
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblHaalandGara))
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblRonaldoGara)))
                .addGap(74, 74, 74)
                .addComponent(ProgressBarMessi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ProgressBarRonaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(ProgressBarNeymar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGaraLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(ProgressBarHaaland, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(789, 789, 789))
        );

        getContentPane().add(panelGara, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void collegaComponenti() {
    // collega immagini — usa i nomi delle tue JLabel nel panelGara
    immaginiCalciatori.put("Messi",   lblMessiGara);
    immaginiCalciatori.put("Ronaldo", lblRonaldoGara);
    immaginiCalciatori.put("Haaland", lblHaalandGara);
    immaginiCalciatori.put("Neymar",  lblNeymarGara);

    // collega progress bar — questi nomi li hai già nel designer
    barreAvanzamento.put("Messi",   ProgressBarMessi);
    barreAvanzamento.put("Ronaldo", ProgressBarRonaldo);
    barreAvanzamento.put("Haaland", ProgressBarHaaland);
    barreAvanzamento.put("Neymar",  ProgressBarNeymar);

    // imposta immagini iniziali
    for (String nome : immaginiCalciatori.keySet()) {
        immaginiCalciatori.get(nome).setIcon(
            caricaIcona(nome.toLowerCase() + "Corre", 80, 100)
        );
    }

    // header "TU:"
    lblTu.setText("TU: " + calciatoreSelezionato.toUpperCase());
    labelTuImg.setIcon(caricaIcona(calciatoreSelezionato.toLowerCase() + "Inizio", 55, 55));
}

private void avviaGara() {
    String[] nomiCalciatori = {"Messi", "Ronaldo", "Haaland", "Neymar"};
    for (String nome : nomiCalciatori) {
        Calciatore calciatore = new Calciatore(nome, this);
        calciatore.setDaemon(true);
        calciatore.start();
    }
}
public void aggiornaPosizioneCalciatore(String nome, int posizione) {
    SwingUtilities.invokeLater(() -> {
        JProgressBar barra = barreAvanzamento.get(nome);
        if (barra != null) barra.setValue(posizione);

        JLabel etichetta = immaginiCalciatori.get(nome);
        if (etichetta != null) {
            int nuovaX = etichetta.getParent().getX() + (int)((posizione / (float) PASSI_ARRIVO) * 660);
            etichetta.setLocation(nuovaX, etichetta.getY());
        }
    });
}

public void calciatoreCaduto(String nome) {
    SwingUtilities.invokeLater(() -> {
        JLabel etichetta = immaginiCalciatori.get(nome);
        if (etichetta != null)
            etichetta.setIcon(caricaIcona(nome.toLowerCase() + "Terra", 80, 100));
    });
    new Thread(() -> {
        try { Thread.sleep(1000); } catch (InterruptedException ignorata) {}
        SwingUtilities.invokeLater(() -> {
            JLabel etichetta = immaginiCalciatori.get(nome);
            if (etichetta != null)
                etichetta.setIcon(caricaIcona(nome.toLowerCase() + "Corre", 80, 100));
        });
    }).start();
}

public void mostraMessaggio(String messaggio) {
    SwingUtilities.invokeLater(() -> {
        testoAvvenimenti.insert(0, "• " + messaggio + "\n");
        jTextArea2.setText(testoAvvenimenti.toString());
    });
}

public synchronized void calciatoreArrivato(String nome) {
    int posto = postoCorrente++;
    SwingUtilities.invokeLater(() -> {
        JProgressBar barra = barreAvanzamento.get(nome);
        if (barra != null) barra.setValue(PASSI_ARRIVO);

        String medaglia = posto == 1 ? "1° 🥇" : posto == 2 ? "2° 🥈" : posto == 3 ? "3° 🥉" : posto + "°";
        classificaFinale.add(medaglia + " " + nome.toUpperCase());
        StringBuilder testo = new StringBuilder();
        for (String riga : classificaFinale) testo.append(riga).append("\n");
        jTextArea1.setText(testo.toString());

        if (nome.equalsIgnoreCase(calciatoreSelezionato)) {
            String esito = posto == 1 ? "HAI VINTO! 🎉" : "Sei arrivato " + posto + "°";
            JOptionPane.showMessageDialog(this, esito, "GARA FINITA", JOptionPane.INFORMATION_MESSAGE);
        }
    });
}

private ImageIcon caricaIcona(String nomeFile, int larghezza, int altezza) {
    try {
        java.net.URL indirizzo = getClass().getResource(
            "/dangelogregoriogarathread/" + nomeFile + ".png");
        if (indirizzo == null) return new ImageIcon();
        Image immagine = new ImageIcon(indirizzo).getImage()
            .getScaledInstance(larghezza, altezza, Image.SCALE_SMOOTH);
        return new ImageIcon(immagine);
    } catch (Exception errore) {
        return new ImageIcon();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBarHaaland;
    private javax.swing.JProgressBar ProgressBarMessi;
    private javax.swing.JProgressBar ProgressBarNeymar;
    private javax.swing.JProgressBar ProgressBarRonaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelTuImg;
    private javax.swing.JLabel lblHaalandGara;
    private javax.swing.JLabel lblMessiGara;
    private javax.swing.JLabel lblNeymarGara;
    private javax.swing.JLabel lblRonaldoGara;
    private javax.swing.JLabel lblTu;
    private javax.swing.JPanel panelClassifica;
    private javax.swing.JPanel panelDestra;
    private javax.swing.JPanel panelGara;
    private javax.swing.JPanel panelImprevisti;
    // End of variables declaration//GEN-END:variables
}
