/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangelogregoriogarathread;


import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
/**
 *
 * @author dange
 */
public class FrameGara extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameGara.class.getName());

    private static final int passiArrivo = 70;
    private String calciatoreSelezionato;

    private final Map<String, JLabel>       immaginiCalciatori = new LinkedHashMap<>();
    private final Map<String, JProgressBar> barreAvanzamento   = new LinkedHashMap<>();

    private final List<String>  classificaFinale = new ArrayList<>();
    private final StringBuilder testoAvvenimenti = new StringBuilder();
    private int postoCorrente = 1;

    
    /**
     * Creates new form FrameGara
     */
    public FrameGara(String nomeCalciatore) {
    this.calciatoreSelezionato = nomeCalciatore;
    initComponents();
    // 1. Rende la finestra non ridimensionabile
    this.setResizable(false);
    // 2. Massimizza la finestra sia orizzontalmente che verticalmente
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    collegaComponenti();
    avviaGara();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTu = new javax.swing.JLabel();
        labelTuImg = new javax.swing.JLabel();
        panelDestra = new javax.swing.JPanel();
        panelClassifica = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelImprevisti = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panelGara = new javax.swing.JPanel();
        lblMessiGara = new javax.swing.JLabel();
        lblRonaldoGara = new javax.swing.JLabel();
        lblHaalandGara = new javax.swing.JLabel();
        lblNeymarGara = new javax.swing.JLabel();
        ProgressBarMessi = new javax.swing.JProgressBar();
        ProgressBarRonaldo = new javax.swing.JProgressBar();
        ProgressBarNeymar = new javax.swing.JProgressBar();
        ProgressBarHaaland = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 40, 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(1690, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblTu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTu.setForeground(new java.awt.Color(255, 255, 255));
        lblTu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTu.setText("TU: ");
        lblTu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblTu, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel1.add(labelTuImg, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelDestra.setBackground(new java.awt.Color(10, 40, 10));
        panelDestra.setPreferredSize(new java.awt.Dimension(350, 0));

        panelClassifica.setBackground(new java.awt.Color(10, 40, 10));
        panelClassifica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLASSIFICA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextArea1.setBackground(new java.awt.Color(10, 20, 10));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelClassificaLayout = new javax.swing.GroupLayout(panelClassifica);
        panelClassifica.setLayout(panelClassificaLayout);
        panelClassificaLayout.setHorizontalGroup(
            panelClassificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClassificaLayout.setVerticalGroup(
            panelClassificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClassificaLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelImprevisti.setBackground(new java.awt.Color(10, 40, 10));
        panelImprevisti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AVVENIMENTI");

        jTextArea2.setBackground(new java.awt.Color(10, 20, 10));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout panelImprevistiLayout = new javax.swing.GroupLayout(panelImprevisti);
        panelImprevisti.setLayout(panelImprevistiLayout);
        panelImprevistiLayout.setHorizontalGroup(
            panelImprevistiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImprevistiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelImprevistiLayout.setVerticalGroup(
            panelImprevistiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprevistiLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDestraLayout = new javax.swing.GroupLayout(panelDestra);
        panelDestra.setLayout(panelDestraLayout);
        panelDestraLayout.setHorizontalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelClassifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelImprevisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDestraLayout.setVerticalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestraLayout.createSequentialGroup()
                .addComponent(panelClassifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImprevisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelDestra, java.awt.BorderLayout.LINE_END);

        panelGara.setBackground(new java.awt.Color(20, 60, 20));
        panelGara.setLayout(null);

        lblMessiGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/messiCorre.png"))); // NOI18N
        lblMessiGara.setPreferredSize(new java.awt.Dimension(130, 130));
        lblMessiGara.setRequestFocusEnabled(false);
        panelGara.add(lblMessiGara);
        lblMessiGara.setBounds(30, 60, 130, 130);

        lblRonaldoGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/ronaldoCorre.png"))); // NOI18N
        lblRonaldoGara.setPreferredSize(new java.awt.Dimension(130, 120));
        panelGara.add(lblRonaldoGara);
        lblRonaldoGara.setBounds(30, 270, 130, 130);

        lblHaalandGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/haalandCorre.png"))); // NOI18N
        lblHaalandGara.setPreferredSize(new java.awt.Dimension(120, 120));
        panelGara.add(lblHaalandGara);
        lblHaalandGara.setBounds(30, 480, 130, 130);

        lblNeymarGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/neymarCorre.png"))); // NOI18N
        lblNeymarGara.setPreferredSize(new java.awt.Dimension(120, 120));
        panelGara.add(lblNeymarGara);
        lblNeymarGara.setBounds(30, 690, 130, 130);

        ProgressBarMessi.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarMessi.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarMessi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));
        ProgressBarMessi.setBorderPainted(false);
        panelGara.add(ProgressBarMessi);
        ProgressBarMessi.setBounds(30, 30, 1280, 180);

        ProgressBarRonaldo.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarRonaldo.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarRonaldo.setBorder(null);
        ProgressBarRonaldo.setBorderPainted(false);
        panelGara.add(ProgressBarRonaldo);
        ProgressBarRonaldo.setBounds(30, 240, 1280, 180);

        ProgressBarNeymar.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarNeymar.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarNeymar.setBorder(null);
        ProgressBarNeymar.setBorderPainted(false);
        panelGara.add(ProgressBarNeymar);
        ProgressBarNeymar.setBounds(30, 660, 1280, 180);

        ProgressBarHaaland.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarHaaland.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarHaaland.setBorder(null);
        ProgressBarHaaland.setBorderPainted(false);
        panelGara.add(ProgressBarHaaland);
        ProgressBarHaaland.setBounds(30, 450, 1280, 180);

        getContentPane().add(panelGara, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void collegaComponenti() {
    // collega immagini — usa i nomi delle tue JLabel nel panelGara
    immaginiCalciatori.put("Messi",   lblMessiGara);
    immaginiCalciatori.put("Ronaldo", lblRonaldoGara);
    immaginiCalciatori.put("Haaland", lblHaalandGara);
    immaginiCalciatori.put("Neymar",  lblNeymarGara);

    // collega progress bar — questi nomi li hai già nel designer
    barreAvanzamento.put("Messi",   ProgressBarMessi);
    barreAvanzamento.put("Ronaldo", ProgressBarRonaldo);
    barreAvanzamento.put("Haaland", ProgressBarHaaland);
    barreAvanzamento.put("Neymar",  ProgressBarNeymar);

    // imposta immagini iniziali
    for (String nome : immaginiCalciatori.keySet()) {
    immaginiCalciatori.get(nome).setIcon(
        caricaIcona(nome.toLowerCase() + "Corre", 120, 120)
    );
}
    for (JProgressBar barra : barreAvanzamento.values()) {
    barra.setMaximum(passiArrivo);
    barra.setMinimum(0);
}

    // header "TU:"
    lblTu.setText("TU: " + calciatoreSelezionato.toUpperCase());
    labelTuImg.setIcon(caricaIcona(calciatoreSelezionato.toLowerCase() + "Inizio", 100, 100));
    
    panelGara.setComponentZOrder(lblMessiGara,   0);
    panelGara.setComponentZOrder(lblRonaldoGara, 1);
    panelGara.setComponentZOrder(lblHaalandGara, 2);
    panelGara.setComponentZOrder(lblNeymarGara,  3);
}

private void avviaGara() {
    String[] nomiCalciatori = {"Messi", "Ronaldo", "Haaland", "Neymar"};
    for (String nome : nomiCalciatori) {
        Calciatore calciatore = new Calciatore(nome, this);
        calciatore.setDaemon(true);
        calciatore.start();
    }
}
public void aggiornaPosizioneCalciatore(String nome, int posizione) {
    SwingUtilities.invokeLater(() -> {
        JProgressBar barra = barreAvanzamento.get(nome);
        if (barra != null) barra.setValue(posizione);

        JLabel etichetta = immaginiCalciatori.get(nome);
        if (etichetta != null) {
            int xInizio = 30;
            int larghezzaBarra = 1280;
            int larghezzaImmagine = etichetta.getWidth();
            int spazioDisponibile = larghezzaBarra - larghezzaImmagine;
            int nuovaX = xInizio + (int)((posizione / (float) passiArrivo) * spazioDisponibile);
            etichetta.setLocation(nuovaX, etichetta.getY());
        }
    });
}

public void calciatoreCaduto(Calciatore calciatore) {
    String nome = calciatore.getNome();
    SwingUtilities.invokeLater(() -> {
        JLabel etichetta = immaginiCalciatori.get(nome);
        if (etichetta != null)
            etichetta.setIcon(caricaIcona(nome.toLowerCase() + "Terra", 120, 120));
    });

    // dopo 2 secondi rialza il calciatore
    new Thread(() -> {
        try { Thread.sleep(2000); } catch (InterruptedException ignorata) {}
        SwingUtilities.invokeLater(() -> {
            JLabel etichetta = immaginiCalciatori.get(nome);
            if (etichetta != null)
                etichetta.setIcon(caricaIcona(nome.toLowerCase() + "Corre", 120, 120));
        });
        calciatore.rialzati(); // sblocca il thread
    }).start();
}

public void mostraMessaggio(String messaggio) {
    SwingUtilities.invokeLater(() -> {
        testoAvvenimenti.insert(0, "• " + messaggio + "\n");
        jTextArea2.setText(testoAvvenimenti.toString());
    });
}

public synchronized void calciatoreArrivato(String nome) {
    int posto = postoCorrente++;
    SwingUtilities.invokeLater(() -> {
        JProgressBar barra = barreAvanzamento.get(nome);
        if (barra != null) barra.setValue(passiArrivo);

        String medaglia = posto == 1 ? "1° 🥇" : posto == 2 ? "2° 🥈" : posto == 3 ? "3° 🥉" : posto + "°";
        classificaFinale.add(medaglia + " " + nome.toUpperCase());
        StringBuilder testo = new StringBuilder();
        for (String riga : classificaFinale) testo.append(riga).append("\n");
        jTextArea1.setText(testo.toString());

        if (nome.equalsIgnoreCase(calciatoreSelezionato)) {
            String esito = posto == 1 ? "HAI VINTO! 🎉" : "Sei arrivato " + posto + "°";
            JOptionPane.showMessageDialog(this, esito, "GARA FINITA", JOptionPane.INFORMATION_MESSAGE);
        }
    });
}

private ImageIcon caricaIcona(String nomeFile, int larghezza, int altezza) {
    try {
        java.net.URL indirizzo = getClass().getResource(
            "/Immagini/" + nomeFile + ".png");
        if (indirizzo == null) return new ImageIcon();
        Image immagine = new ImageIcon(indirizzo).getImage()
            .getScaledInstance(larghezza, altezza, Image.SCALE_SMOOTH);
        return new ImageIcon(immagine);
    } catch (Exception errore) {
        return new ImageIcon();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBarHaaland;
    private javax.swing.JProgressBar ProgressBarMessi;
    private javax.swing.JProgressBar ProgressBarNeymar;
    private javax.swing.JProgressBar ProgressBarRonaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelTuImg;
    private javax.swing.JLabel lblHaalandGara;
    private javax.swing.JLabel lblMessiGara;
    private javax.swing.JLabel lblNeymarGara;
    private javax.swing.JLabel lblRonaldoGara;
    private javax.swing.JLabel lblTu;
    private javax.swing.JPanel panelClassifica;
    private javax.swing.JPanel panelDestra;
    private javax.swing.JPanel panelGara;
    private javax.swing.JPanel panelImprevisti;
    // End of variables declaration//GEN-END:variables
}
