/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dangelogregoriogarathread;

import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 * gestisce la finestra principale della gara mostra i calciatori che corrono
 * con le progress bar
 *
 * @author dange
 */
public class FrameGara extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameGara.class.getName());

    // num di passi che servono per arrivare al traguardo
    private static final int passiArrivo = 100;
    private String calciatoreSelezionato;

    // mappa che collega il nome del calciatore alla sua immagine nella finestra
    private final Map<String, JLabel> immaginiCalciatori = new LinkedHashMap<>();
    // mappa che collega il nome del calciatore alla sua barra di avanzamento
    private final Map<String, JProgressBar> barreAvanzamento = new LinkedHashMap<>();

    private final List<String> classificaFinale = new ArrayList<>();
    private final StringBuilder testoAvvenimenti = new StringBuilder();
    private int postoCorrente = 1;

    /**
     * costruttore
     * riceve il nome del calciatore scelto dal giocatore nella schermata precedente
     *
     * @param nomeCalciatore calciatore scelto dall'utente
     */
    public FrameGara(String nomeCalciatore) {
        this.calciatoreSelezionato = nomeCalciatore;
        initComponents();
        //Rende la finestra non ridimensionabile
        this.setResizable(false);
        //ingrandisce la schermata a tutto schermo
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        calcolaScala();
        collegaComponenti();
        ridimensionaComponenti();
        avviaGara();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTu = new javax.swing.JLabel();
        labelTuImg = new javax.swing.JLabel();
        panelDestra = new javax.swing.JPanel();
        panelClassifica = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelImprevisti = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panelGara = new javax.swing.JPanel();
        lblMessiGara = new javax.swing.JLabel();
        lblRonaldoGara = new javax.swing.JLabel();
        lblHaalandGara = new javax.swing.JLabel();
        lblNeymarGara = new javax.swing.JLabel();
        ProgressBarMessi = new javax.swing.JProgressBar();
        ProgressBarRonaldo = new javax.swing.JProgressBar();
        ProgressBarNeymar = new javax.swing.JProgressBar();
        ProgressBarHaaland = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 40, 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(1690, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblTu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTu.setForeground(new java.awt.Color(255, 255, 255));
        lblTu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTu.setText("TU: ");
        lblTu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblTu, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel1.add(labelTuImg, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelDestra.setBackground(new java.awt.Color(10, 40, 10));
        panelDestra.setPreferredSize(new java.awt.Dimension(350, 0));

        panelClassifica.setBackground(new java.awt.Color(10, 40, 10));
        panelClassifica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLASSIFICA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextArea1.setBackground(new java.awt.Color(10, 20, 10));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelClassificaLayout = new javax.swing.GroupLayout(panelClassifica);
        panelClassifica.setLayout(panelClassificaLayout);
        panelClassificaLayout.setHorizontalGroup(
            panelClassificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClassificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClassificaLayout.setVerticalGroup(
            panelClassificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClassificaLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelImprevisti.setBackground(new java.awt.Color(10, 40, 10));
        panelImprevisti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AVVENIMENTI");

        jTextArea2.setBackground(new java.awt.Color(10, 20, 10));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout panelImprevistiLayout = new javax.swing.GroupLayout(panelImprevisti);
        panelImprevisti.setLayout(panelImprevistiLayout);
        panelImprevistiLayout.setHorizontalGroup(
            panelImprevistiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImprevistiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelImprevistiLayout.setVerticalGroup(
            panelImprevistiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprevistiLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDestraLayout = new javax.swing.GroupLayout(panelDestra);
        panelDestra.setLayout(panelDestraLayout);
        panelDestraLayout.setHorizontalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelClassifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelImprevisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDestraLayout.setVerticalGroup(
            panelDestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestraLayout.createSequentialGroup()
                .addComponent(panelClassifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImprevisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelDestra, java.awt.BorderLayout.LINE_END);

        panelGara.setBackground(new java.awt.Color(20, 60, 20));
        panelGara.setLayout(null);

        lblMessiGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/messiCorre.png"))); // NOI18N
        lblMessiGara.setPreferredSize(new java.awt.Dimension(130, 130));
        lblMessiGara.setRequestFocusEnabled(false);
        panelGara.add(lblMessiGara);
        lblMessiGara.setBounds(30, 60, 130, 130);

        lblRonaldoGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/ronaldoCorre.png"))); // NOI18N
        lblRonaldoGara.setPreferredSize(new java.awt.Dimension(130, 120));
        panelGara.add(lblRonaldoGara);
        lblRonaldoGara.setBounds(30, 270, 130, 130);

        lblHaalandGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/haalandCorre.png"))); // NOI18N
        lblHaalandGara.setPreferredSize(new java.awt.Dimension(120, 120));
        panelGara.add(lblHaalandGara);
        lblHaalandGara.setBounds(30, 480, 130, 130);

        lblNeymarGara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/neymarCorre.png"))); // NOI18N
        lblNeymarGara.setPreferredSize(new java.awt.Dimension(120, 120));
        panelGara.add(lblNeymarGara);
        lblNeymarGara.setBounds(30, 690, 130, 130);

        ProgressBarMessi.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarMessi.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarMessi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 180, 80)));
        ProgressBarMessi.setBorderPainted(false);
        panelGara.add(ProgressBarMessi);
        ProgressBarMessi.setBounds(30, 30, 1280, 180);

        ProgressBarRonaldo.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarRonaldo.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarRonaldo.setBorder(null);
        ProgressBarRonaldo.setBorderPainted(false);
        panelGara.add(ProgressBarRonaldo);
        ProgressBarRonaldo.setBounds(30, 240, 1280, 180);

        ProgressBarNeymar.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarNeymar.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarNeymar.setBorder(null);
        ProgressBarNeymar.setBorderPainted(false);
        panelGara.add(ProgressBarNeymar);
        ProgressBarNeymar.setBounds(30, 660, 1280, 180);

        ProgressBarHaaland.setBackground(new java.awt.Color(20, 60, 20));
        ProgressBarHaaland.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBarHaaland.setBorder(null);
        ProgressBarHaaland.setBorderPainted(false);
        panelGara.add(ProgressBarHaaland);
        ProgressBarHaaland.setBounds(30, 450, 1280, 180);

        getContentPane().add(panelGara, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * collega i componenti grafici creati da netbeans alle mappe
     * cosi posso aggiornarli durante la gara usando solo il nome del calciatore
     */
    private void collegaComponenti() {
        // collega ogni nome alla sua etichetta immagine
        immaginiCalciatori.put("Messi", lblMessiGara);
        immaginiCalciatori.put("Ronaldo", lblRonaldoGara);
        immaginiCalciatori.put("Haaland", lblHaalandGara);
        immaginiCalciatori.put("Neymar", lblNeymarGara);

        // collega ogni nome alla sua progress bar
        barreAvanzamento.put("Messi", ProgressBarMessi);
        barreAvanzamento.put("Ronaldo", ProgressBarRonaldo);
        barreAvanzamento.put("Haaland", ProgressBarHaaland);
        barreAvanzamento.put("Neymar", ProgressBarNeymar);

        // carica le immagini iniziali dei calciatori che corrono
        for (String nome : immaginiCalciatori.keySet()) {
            immaginiCalciatori.get(nome).setIcon(caricaIcona(nome.toLowerCase() + "Corre", 120, 120));
        }
        // imposta il massimo di ogni barra uguale ai passi per arrivare
        for (JProgressBar barra : barreAvanzamento.values()) {
            barra.setMaximum(passiArrivo);
            barra.setMinimum(0);
        }

        // mostra in alto il calciatore scelto con la sua immagine
        lblTu.setText("TU: " + calciatoreSelezionato.toUpperCase());
        labelTuImg.setIcon(caricaIcona(calciatoreSelezionato.toLowerCase() + "Inizio", 100, 100));

        panelGara.setComponentZOrder(lblMessiGara, 0);
        panelGara.setComponentZOrder(lblRonaldoGara, 1);
        panelGara.setComponentZOrder(lblHaalandGara, 2);
        panelGara.setComponentZOrder(lblNeymarGara, 3);
    }

    private double scalaX;
    private double scalaY;

    /**
     * calcola i fattori di scala confrontando la risoluzione reale dello 
     * schermo con quella su cui ho sviluppato il progetto (1920x1080) va 
     * chiamata prima di tutto il resto nel costruttore
     */
    private void calcolaScala() {
        // prende la dimensione reale dello schermo
        java.awt.Dimension schermo = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
         // 1920 e 1080 misure dove ho sviluppato tutto
        scalaX = schermo.getWidth() / 1920.0;
        scalaY = schermo.getHeight() / 1080.0;
    }
    
    /**
     * ridimensiona tutti i componenti del panelGara in base ai fattori di scala
     * calcolati aggiorna le bounds delle progress bar, delle label e le
     * dimensioni delle icone va chiamata dopo collegaComponenti e prima di
     * avviaGara
     */
    private void ridimensionaComponenti() {
        // ridimensiona ogni label immagine e la sua progress bar in base allo schermo
        int xInizio = (int) (30 * scalaX);
        int larghezza = (int) (1280 * scalaX);

        int yMessi = (int) (30 * scalaY);
        int yRonaldo = (int) (240 * scalaY);
        int yHaaland = (int) (450 * scalaY);
        int yNeymar = (int) (660 * scalaY);
        int altezzaRiga = (int) (180 * scalaY);
        int dimImg = (int) (120 * scalaY);

        lblMessiGara.setBounds(xInizio, (int) (60 * scalaY), dimImg, dimImg);
        lblRonaldoGara.setBounds(xInizio, (int) (270 * scalaY), dimImg, dimImg);
        lblHaalandGara.setBounds(xInizio, (int) (480 * scalaY), dimImg, dimImg);
        lblNeymarGara.setBounds(xInizio, (int) (690 * scalaY), dimImg, dimImg);

        ProgressBarMessi.setBounds(xInizio, yMessi, larghezza, altezzaRiga);
        ProgressBarRonaldo.setBounds(xInizio, yRonaldo, larghezza, altezzaRiga);
        ProgressBarHaaland.setBounds(xInizio, yHaaland, larghezza, altezzaRiga);
        ProgressBarNeymar.setBounds(xInizio, yNeymar, larghezza, altezzaRiga);

        // aggiorna anche le icone con la nuova dimensione scalata
        for (String nome : immaginiCalciatori.keySet()) {
            immaginiCalciatori.get(nome).setIcon(
                    caricaIcona(nome.toLowerCase() + "Corre", dimImg, dimImg)
            );
        }
    }
    /**
     * crea un thread per ogni calciatore e li avvia tutti insieme
     * ogni thread gestisce il movimento indipendente del proprio calciatore
     * setdaemon true fa si che i thread si chiudano quando si chiude la finestra
     */
    private void avviaGara() {
        String[] nomiCalciatori = {"Messi", "Ronaldo", "Haaland", "Neymar"};
        for (String nome : nomiCalciatori) {
            Calciatore calciatore = new Calciatore(nome, this);
            calciatore.setDaemon(true);
            calciatore.start();
        }
    }

     /**
     * aggiorna la progress bar e sposta l'immagine del calciatore nella finestra
     * viene chiamato dal thread del calciatore ogni volta che avanza di un passo
     *
     * @param nome il nome del calciatore da aggiornare
     * @param posizione la posizione attuale del calciatore da 0 a passiArrivo
     */
    public void aggiornaPosizioneCalciatore(String nome, int posizione) {
        // invokeLater serve ai thread per non  modificare la grafica direttamente
        // tutte le modifiche ai componenti swing vanno fatte nel thread dell'interfaccia
        SwingUtilities.invokeLater(() -> {
            JProgressBar barra = barreAvanzamento.get(nome);
            if (barra != null) {
                barra.setValue(posizione);
            }

            JLabel etichetta = immaginiCalciatori.get(nome);
            if (etichetta != null) {
                int xInizio = 30;
                int larghezzaBarra = (int)(1280 * scalaX);
                int larghezzaImmagine = etichetta.getWidth();
                int spazioDisponibile = larghezzaBarra - larghezzaImmagine;
                 // calcola la x proporzionale alla posizione del calciatore sulla barra
                int nuovaX = xInizio + (int) ((posizione / (float) passiArrivo) * spazioDisponibile);
                etichetta.setLocation(nuovaX, etichetta.getY());
            }
        });
    }

    /**
     * gestisce la caduta di un calciatore cambiando la sua immagine
     * dopo 2 secondi lo rialza e sblocca il suo thread cosi puo riprendere a correre
     *
     * @param calciatore il calciatore che e caduto
     */
    public void calciatoreCaduto(Calciatore calciatore) {
        String nome = calciatore.getNome();
        SwingUtilities.invokeLater(() -> { // invokeLater serve ai thread per non  modificare la grafica direttamente
            JLabel etichetta = immaginiCalciatori.get(nome);
            if (etichetta != null) {
                 // mostra l'immagine del calciatore a terra
                etichetta.setIcon(caricaIcona(nome.toLowerCase() + "Terra", (int)(120 * scalaY), (int)(120 * scalaY)));
            }
        });

        // dopo 1,5 secondi rialza il calciatore
        new Thread(() -> {
            try {
                Thread.sleep(1500);
            } catch (InterruptedException ignorata) {
            }
            SwingUtilities.invokeLater(() -> { // invokeLater serve ai thread per non  modificare la grafica direttamente
                JLabel etichetta = immaginiCalciatori.get(nome);
                if (etichetta != null) {
                    etichetta.setIcon(caricaIcona(nome.toLowerCase() + "Corre", (int)(120 * scalaY), (int)(120 * scalaY)));
                }
            });
            calciatore.rialzati(); // sblocca il thread
        }).start();
    }

    /**
     * aggiunge un messaggio in cima alla lista degli avvenimenti
     * insert(0) fa si che i messaggi nuovi appaiano sempre in alto
     *
     * @param messaggio il testo dell'avvenimento da mostrare
     */
    public void mostraMessaggio(String messaggio) {
        SwingUtilities.invokeLater(() -> { // invokeLater serve ai thread per non  modificare la grafica direttamente
            testoAvvenimenti.insert(0, "• " + messaggio + "\n");
            jTextArea2.setText(testoAvvenimenti.toString());
        });
    }

    /**
     * viene chiamato quando un calciatore arriva al traguardo
     * synchronized evita che due calciatori prendano lo stesso posto in classifica
     * se il calciatore scelto dal giocatore arriva mostra un messaggio con il ris
     *
     * @param nome il nome del calciatore arrivato
     */
    public synchronized void calciatoreArrivato(String nome) {
        int posto = postoCorrente++;
        SwingUtilities.invokeLater(() -> { // invokeLater serve ai thread per non  modificare la grafica direttamente
            JProgressBar barra = barreAvanzamento.get(nome);
            if (barra != null) {
                barra.setValue(passiArrivo);
            }

            String ris = posto == 1 ? "1° " : posto == 2 ? "2° " : posto == 3 ? "3° " : posto + "°";
            classificaFinale.add(ris + " " + nome.toUpperCase());
            StringBuilder testo = new StringBuilder();
            for (String riga : classificaFinale) {
                testo.append(riga).append("\n");
            }
            jTextArea1.setText(testo.toString());

            if (nome.equalsIgnoreCase(calciatoreSelezionato)) {
                String esito = posto == 1 ? "HAI VINTO " : "sei arrivato " + posto + "°";
                JOptionPane.showMessageDialog(this, esito, "--GARA FINITA--", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }

    /**
     * carica un immagine dalla cartella immagini e la ridimensiona
     * se il file non esiste restituisce un icona vuota senza mandare in crash il programma
     *
     * @param nomeFile il nome del file senza estensione
     * @param larghezza larghezza desiderata in pixel
     * @param altezza altezza desiderata in pixel
     * @return l'icona ridimensionata oppure un icona vuota se non trovata
     */
    private ImageIcon caricaIcona(String nomeFile, int larghezza, int altezza) {
        try {
            java.net.URL indirizzo = getClass().getResource(
                    "/Immagini/" + nomeFile + ".png");
            if (indirizzo == null) {
                return new ImageIcon();
            }
            Image immagine = new ImageIcon(indirizzo).getImage()
                    .getScaledInstance(larghezza, altezza, Image.SCALE_SMOOTH);  // SCALE_SMOOTH rende l'immagine piu nitida quando viene ridimensionata
            return new ImageIcon(immagine);
        } catch (Exception errore) {
            return new ImageIcon();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBarHaaland;
    private javax.swing.JProgressBar ProgressBarMessi;
    private javax.swing.JProgressBar ProgressBarNeymar;
    private javax.swing.JProgressBar ProgressBarRonaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelTuImg;
    private javax.swing.JLabel lblHaalandGara;
    private javax.swing.JLabel lblMessiGara;
    private javax.swing.JLabel lblNeymarGara;
    private javax.swing.JLabel lblRonaldoGara;
    private javax.swing.JLabel lblTu;
    private javax.swing.JPanel panelClassifica;
    private javax.swing.JPanel panelDestra;
    private javax.swing.JPanel panelGara;
    private javax.swing.JPanel panelImprevisti;
    // End of variables declaration//GEN-END:variables
}
